Add DTO tmPost, apiConst, entity tmPost, read and create endpoints
ApenDover/tm pull request #1
Opened 2024-03-09 16:32 UTC by ApenDover

2024-03-09 17:58 UTC, dlxgit requested changes
Выглядит неплохо, не хватает подкованности в том как писать. Но свою роль вроде код выполняет. Из-за того что кода написано как по мне дохрена, придется рефакторить больше кода. Вообще. Хотелось бы по кирпичикам объяснять (прям с микро изменений с нуля как писать). У тебя же сейчас много кода. И ошибок много. И исправления потребуются большие. Если хочешь освоить всякие штуки, не стоит заострять внимание на "бизнес коде". Нужно заострить внимание на концепции написания кода. И уменьшить дозировки кода.

2024-03-09 17:58 UTC, dlxgit commented on src/test/java/ts/andrey/tm/controller/EndPointAuthTest.java
>  	void SUCCESS_PATH() throws Exception {
если у тебя тесты кидают исключения лучше использовать ломбок SneakyThrows. Если не понятно почему могу потом рассказать. Концептуально это одно и то же, но сники троуз был задуман именно для этого (я так думаю)

2024-03-09 17:58 UTC, dlxgit commented on src/test/java/ts/andrey/tm/controller/EndPointAuthTest.java
>  	}
Не понятно че за папка data в проекте. Давай ее не будет, сделаем папку Entity и папку Repository.
Services - не понятно че это. И чем отличается от Service. Наличие Services и Service это помойму хрень

2024-03-09 17:58 UTC, dlxgit commented on src/main/java/ts/andrey/tm/tmconst/ApiConst.java
> +    public static final String ALL_GET_POST = "/read/tmpost";
давай соблюдать стиль rest. Для архитектуры api. Никаких read и create. Мы же делаем эталонный проект

2024-03-09 17:58 UTC, dlxgit commented on src/test/java/ts/andrey/tm/controller/EndPointAuthTest.java
>  @AutoConfigureMockMvc
Я ненавижу Mock mvc. И не вижу в нем прикола. Хотя многие любят. Любят в основном тестировщики. Потому что он создан для упрощения тестирования бизнес фич. В работу программиста входит немного шире чем тестирование бизнес фич. И я пишу всегда тесты на "целых серверах". Без урезаний и моков. Например в мок mvc вроде не получится дернуть метрики, нет актуатора и тд. Есть куча других моментов которых там нет. Реальный сервер не поднимается и тесты которые расчитаны не на проверку бизнеса а на инфраструктуру могут вести себя не так. Ну и получается миксовать не выйдет абстрактную реализацию для MockMvc и для реального сервера. Нужно две абстрактные реализации. Это хрень. Не люблю я такое. Не вижу плюсов никаких.

2024-03-09 17:58 UTC, dlxgit commented on src/test/java/ts/andrey/tm/controller/TmControllerTest.java
> +class TmControllerTest {
Сделай абстрактную реализацию чтобы не нужно было в каждом тесте писать SpringBootTest.
Если тест интеграционный оканчивай его на IT (integration test). Если нет то просто Test.

2024-03-09 17:58 UTC, dlxgit commented on src/test/java/ts/andrey/tm/controller/TmControllerTest.java
> +@ActiveProfiles("test")
Попробуй без профиля test.
Для этого нужно переименовать файл application-test.yml в тестах

2024-03-09 17:58 UTC, dlxgit commented on src/test/java/ts/andrey/tm/controller/TmControllerTest.java
> +        mockMvc.perform(MockMvcRequestBuilders.post(ApiConst.ALL_CREATE_POST_API)
GIVEN when then не должно 2 действия быть в WHEN.

2024-03-09 17:58 UTC, dlxgit commented on src/test/java/ts/andrey/tm/controller/TmControllerTest.java
> +                objectMapper.getTypeFactory().constructCollectionType(List.class, TmPostDto.class));
Какой нафиг ObjectMapper. За тебя спринг должен все сделать по идее

2024-03-09 17:58 UTC, dlxgit commented on src/test/java/ts/andrey/tm/mapper/TmPostMapperTest.java
> +
Давай без лишней строчки пустой. Везде убери

2024-03-09 17:58 UTC, dlxgit commented on src/test/java/ts/andrey/tm/mapper/TmPostMapperTest.java
> +            Mappers.getMapper(TmPostMapper.class);
Длина строки позволяет писать без новой строки

2024-03-09 17:58 UTC, dlxgit commented on src/main/java/ts/andrey/tm/service/CrudPostService.java
> +public class CrudPostService {
Не должно быть слова Crud.

2024-03-09 17:58 UTC, dlxgit commented on src/test/resources/postman/taskmanager.postman_collection.json
>  			"response": []
Постман не должен лежать в тестах. Пусть он лежит в корне. В папке postman

2024-03-09 17:58 UTC, dlxgit commented on src/test/java/ts/andrey/tm/controller/EndPointAuthTest.java
>  	void SUCCESS_PATH() throws Exception {
Нарушение стиля именования методов

2024-03-09 17:58 UTC, dlxgit commented on src/test/java/ts/andrey/tm/mapper/TmPostMapperTest.java
> +        final var tmPostDtoActual = mapper.toDto(tmPostActual);
Не должно быть два действия в WHEN

2024-03-09 17:58 UTC, dlxgit commented on src/main/java/ts/andrey/tm/controller/TmController.java
> +        log.info("request to {}: {}", ApiConst.ALL_CREATE_POST, postDto);
Запросы логируются и так я не уверен что это имеет смысл.  Нужно просто найти нужный логер спринга. Можешь поискать "полезные логи" кое-где

2024-03-09 17:58 UTC, dlxgit commented on src/main/java/ts/andrey/tm/controller/TmController.java
> +    @GetMapping(ApiConst.ALL_GET_POST)
Давай проектировать по рест стилю

2024-03-09 17:58 UTC, dlxgit commented on src/main/java/ts/andrey/tm/controller/TmController.java
> +        return "added";
Результат пост запроса должен быть Объект который сохранен с кое-каким статусом Http (НЕ 200).

2024-03-09 17:58 UTC, dlxgit commented on src/main/java/ts/andrey/tm/data/entity/TmPost.java
> +public class TmPost {
Давай все Entity называть ...Entity

2024-03-09 17:58 UTC, dlxgit commented on src/main/java/ts/andrey/tm/data/repository/TmPostRepository.java
> +public interface TmPostRepository extends JpaRepository<TmPost, Integer> {
На все репозитории и сервисы пиши всегда тесты.

2024-03-09 17:58 UTC, dlxgit commented on src/main/java/ts/andrey/tm/data/repository/TmPostRepository.java
> +    int getLastValFromSequence();
Зачем тебе такое?) Я пока не вникал, может когда-то вникну, но реакция такая себе

2024-03-09 17:58 UTC, dlxgit commented on src/main/java/ts/andrey/tm/data/services/TmPostService.java
> +public class TmPostService {
Ты должен написать unit тесты на этот класс. Вообще все сервисы всегда требуют юнит тестов. Ознакомься что такое пирамида тестирования. И в какую сторону она строится. И почему много юнит тестов нужно и мало интеграционных. В целом бывает когда сервис лучше покрыть интергационно, но это редко

2024-03-09 17:58 UTC, dlxgit commented on src/main/java/ts/andrey/tm/data/services/TmPostService.java
> +public class TmPostService {
Когда начнешь писать тесты поймешь что код говно, потому что ты никак нормально не протестируешь грязные функции. Тестировать сервис = прежде всего передать аргументы и получить ответ. У тебя же везде void

2024-03-09 17:58 UTC, dlxgit commented on src/main/java/ts/andrey/tm/service/CrudPostService.java
> +        return true;
Везде у всех сервисов  как минимум, заполняй javadoc.

2024-03-09 17:58 UTC, dlxgit commented on src/main/java/ts/andrey/tm/service/CrudPostService.java
> +
Все сервисы нужно абстрагировать от реализации. Чтобы инжектился интерфейс. Таким образом у сервиса будет его интерфейс, и реализация ...Impl.

2024-03-10 06:26 UTC, ApenDover commented on src/main/java/ts/andrey/tm/tmconst/ApiConst.java
> +    public static final String ALL_GET_POST = "/read/tmpost";
делать два endPoint одинаковыми с разницей в http методах (POST/GET) ? я бы все равно разделил их, например так: POST /tmpost/create (для создания новой записи) и GET /tmpost (для чтения всех)

2024-03-10 12:06 UTC, ApenDover commented on src/test/java/ts/andrey/tm/controller/TmControllerTest.java
> +@ActiveProfiles("test")
ok, разницы нет, давай уберем

2024-03-10 12:18 UTC, ApenDover commented on src/test/java/ts/andrey/tm/controller/TmControllerTest.java
> +        mockMvc.perform(MockMvcRequestBuilders.post(ApiConst.ALL_CREATE_POST_API)
первым действием записали данные, вторым прочитали. Сравниваем переданные объекты с полученными, таким образом одним тестом покрыли кучу логики. Думаешь стоит растаскивать на несколько тестов?
Какие аргументы против того, чтобы в WHEN не было двух действий?

2024-03-10 12:31 UTC, ApenDover commented on src/test/java/ts/andrey/tm/controller/TmControllerTest.java
> +                objectMapper.getTypeFactory().constructCollectionType(List.class, TmPostDto.class));
mockMvc умеет только String ответ отдавать. Я не против уйти от mockMvc

2024-03-10 13:20 UTC, ApenDover commented on src/main/java/ts/andrey/tm/service/CrudPostService.java
> +public class CrudPostService {
Верю, но почему нет? Сервис включается в себя create read на данный момент, возможно добавятся update и delete, CrudPostService выглядит говорящим названием. Думаешь лучше растаскать каждое действие на отдельный класс?

2024-03-10 13:23 UTC, ApenDover commented on src/test/java/ts/andrey/tm/mapper/TmPostMapperTest.java
> +        final var tmPostDtoActual = mapper.toDto(tmPostActual);
в одном маппере два метода которые обратны друг другу. Тут очень удобно в одном тесте все покрыть. Почему не должно? Предлагаешь растаскать на два теста?

2024-03-10 13:26 UTC, ApenDover commented on src/main/java/ts/andrey/tm/controller/TmController.java
> +    @GetMapping(ApiConst.ALL_GET_POST)
в данном случае имеешь ввиду название константы или то, что за ней (ты писал выше). Название константы из такой логики: ALL (кто имеет доступ all, user, admin) _ GET_POST (что делает)

2024-03-10 13:47 UTC, dlxgit commented on src/main/java/ts/andrey/tm/tmconst/ApiConst.java
> +    public static final String ALL_GET_POST = "/read/tmpost";
Давай сделаем полный rest. Это все таки учебный проект.

2024-03-10 14:50 UTC, ApenDover commented on src/main/java/ts/andrey/tm/data/repository/TmPostRepository.java
> +    int getLastValFromSequence();
генерация id происходит на этапе вставки новой записи в таблицу. Для того чтобы childPost привязать к родителю нужно знать id родителя. Перед мапингом в entity сразу узнаем какой будет id родителя и проставляем его всем childPost.

2024-06-29 14:01 UTC, merged